name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v3

      - name: Build Backend
        run: docker build -t amit3001muz/backend ./backend

      - name: Push Backend
        run: docker push amit3001muz/backend

      - name: Deploy
        run: kubectl apply -f k8s/